import { initI18n, setLanguage, getLanguage, tr } from './i18n.js?v=0.4.1';
const { invoke } = window.__TAURI__.core;
const { listen } = window.__TAURI__.event;
let tabs=[],active=0,seq=0,internalView=null,groups=[],profiles=[],profileId='default',tabContextId=null,dragTabId=null,dragStartX=0,dragStartY=0,draggingTabs=false,suppressTabClick=false;
const el=id=>document.getElementById(id);
const rawGet=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d));}catch{return d;}};
const rawSet=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const PROFILE_LIST_KEY='veyra.profiles.v1',PROFILE_ACTIVE_KEY='veyra.activeProfile.v1';
const PROFILE_COLORS=['#4f8cff','#9b5cff','#18b981','#f59e0b','#ef5b71','#22b6d8','#e879f9'];
const profilePrefix=()=>`veyra.profile.${profileId}.`;
const jget=(k,d)=>rawGet(profilePrefix()+k,d),jset=(k,v)=>rawSet(profilePrefix()+k,v);
const pstr=(k,d='')=>localStorage.getItem(profilePrefix()+k)??d,pset=(k,v)=>localStorage.setItem(profilePrefix()+k,v);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const saved=()=>jget('veyra.bookmarks',[]),historyList=()=>jget('veyra.history',[]),downloads=()=>jget('veyra.downloads',[]);
const SESSION_KEY='veyra.session.v1',GROUPS_KEY='veyra.groups.v1';
const SLEEP_CHECK_MS=30000;
const sleepMinutes=()=>{const n=Number(pstr('veyra.sleep.minutes','10'));return Number.isFinite(n)&&n>=0?n:10;};
function initProfiles(){
  profiles=rawGet(PROFILE_LIST_KEY,[]);if(!profiles.length){profiles=[{id:'default',name:'Principal',color:PROFILE_COLORS[0]}];rawSet(PROFILE_LIST_KEY,profiles);}
  profileId=localStorage.getItem(PROFILE_ACTIVE_KEY)||profiles[0].id;if(!profiles.some(p=>p.id===profileId))profileId=profiles[0].id;localStorage.setItem(PROFILE_ACTIVE_KEY,profileId);
  if(profileId==='default'&&!localStorage.getItem(profilePrefix()+SESSION_KEY)){['veyra.bookmarks','veyra.history','veyra.downloads',SESSION_KEY].forEach(k=>{const v=localStorage.getItem(k);if(v!==null)localStorage.setItem(profilePrefix()+k,v);});['veyra.search','veyra.theme'].forEach(k=>{const v=localStorage.getItem(k);if(v!==null)localStorage.setItem(profilePrefix()+k,v);});}
}
function saveSession(){jset(SESSION_KEY,{tabs:tabs.map(({id,title,url,groupId,sleeping,lastActive})=>({id,title,url,groupId:groupId||null,sleeping:!!sleeping,lastActive:lastActive||Date.now()})),active,seq});jset(GROUPS_KEY,groups);}
function restoreSession(){
  groups=jget(GROUPS_KEY,[]);const s=jget(SESSION_KEY,null);if(!s||!Array.isArray(s.tabs)||!s.tabs.length)return false;
  tabs=s.tabs.filter(t=>Number.isFinite(Number(t.id))&&(!t.url||/^https?:\/\//i.test(t.url))).map(t=>({id:Number(t.id),title:t.title||'Nova aba',url:t.url||'',groupId:t.groupId||null,loaded:false,sleeping:!!t.sleeping,lastActive:Number(t.lastActive)||Date.now()}));
  if(!tabs.length)return false;seq=Math.max(Number(s.seq)||0,...tabs.map(t=>t.id));active=tabs.some(t=>t.id===Number(s.active))?Number(s.active):tabs[0].id;return true;
}
const engines = {
  google:q => 'https://www.google.com/search?q=' + encodeURIComponent(q),
  duck:q => 'https://duckduckgo.com/?q=' + encodeURIComponent(q),
  bing:q => 'https://www.bing.com/search?q=' + encodeURIComponent(q)
};
function makeUrl(value){
  value=value.trim(); if(!value) return '';
  if(/^https?:\/\//i.test(value)) return value;
  if(/^[\w.-]+\.[a-z]{2,}(\/.*)?$/i.test(value) && !value.includes(' ')) return 'https://' + value;
  const e=pstr('veyra.search','google');
  return (engines[e] || engines.google)(value);
}
function current(){ return tabs.find(t=>t.id===active); }
function isBookmarked(){ const u=current()?.url; return !!u && saved().some(x=>x.url===u); }
function updateStar(){ const b=el('bookmark'); if(!b)return; b.textContent=isBookmarked()?'★':'☆'; b.classList.toggle('active',isBookmarked()); }
const profileMeta=()=>profiles.find(p=>p.id===profileId)||profiles[0];
const extensionsEnabled=()=>pstr('veyra.extensions.enabled','1')!=='0';
const adblockEnabled=()=>pstr('veyra.adblock.enabled','1')!=='0';
function updateProfileButton(){const p=profileMeta();if(!p||!el('topProfile'))return;const initial=(p.name?.[0]||'P').toUpperCase();el('topProfile').textContent=initial;el('topProfile').title=`Perfil: ${p.name}`;el('topProfile').style.color=p.color||'#9fb7ff';['profileBadgeMini','profileBadgeSide'].forEach(id=>{const b=el(id);if(!b)return;b.textContent=initial;b.style.background=p.color||'#4f8cff';b.classList.toggle('show',profiles.length>1);});}
function tabNode(t){const tab=document.createElement('div');tab.className='tab'+(t.id===active?' active':'')+(t.groupId?' grouped':'')+(t.sleeping?' sleeping':'');tab.dataset.id=t.id;tab.draggable=false;tab.title=t.sleeping?'Aba adormecida · abre para recarregar':t.title;const g=groups.find(x=>x.id===t.groupId);if(g)tab.style.setProperty('--group-color',g.color);const name=document.createElement('span');name.textContent=(t.sleeping?'◌ ':'')+t.title;const close=document.createElement('b');close.textContent='×';close.dataset.close=t.id;tab.append(name,close);return tab;}
function render(){
  const host=el('tabs');host.textContent='';const drawn=new Set();
  tabs.forEach(t=>{const g=groups.find(x=>x.id===t.groupId);if(g){if(drawn.has(g.id))return;drawn.add(g.id);const pill=document.createElement('button');pill.className='tab-group-pill';pill.dataset.groupId=g.id;pill.style.setProperty('--group-color',g.color);pill.innerHTML=`<i></i><span>${esc(g.name)}</span>`;host.append(pill);if(!g.collapsed)tabs.filter(x=>x.groupId===g.id).forEach(x=>host.append(tabNode(x)));}else host.append(tabNode(t));});
  el('address').value=current()?.url||'';document.body.classList.toggle('browsing',!!current()?.url&&!internalView);updateStar();updateProfileButton();saveSession();
}
function newTab(groupId=null){tabs.push({id:++seq,title:'Nova aba',url:'',groupId,loaded:false,sleeping:false,lastActive:Date.now()});active=seq;internalView=null;render();invoke('hide_browser');if(el('status'))el('status').innerHTML='<i></i>Pronto';setTimeout(()=>el('address')?.focus(),30);}
function createGroup(){const name=window.prompt('Nome do grupo de abas:','Novo grupo');if(!name)return;const g={id:'g'+Date.now().toString(36),name,color:PROFILE_COLORS[groups.length%PROFILE_COLORS.length],collapsed:false};groups.push(g);if(current())current().groupId=g.id;render();renderGroupMenu();}
function assignGroup(id){if(current())current().groupId=id||null;render();renderGroupMenu();}
function deleteGroup(id){tabs.forEach(t=>{if(t.groupId===id)t.groupId=null;});groups=groups.filter(g=>g.id!==id);render();renderGroupMenu();}
function cycleGroupColor(id){const g=groups.find(x=>x.id===id);if(!g)return;const i=PROFILE_COLORS.indexOf(g.color);g.color=PROFILE_COLORS[(i+1+PROFILE_COLORS.length)%PROFILE_COLORS.length];render();renderGroupMenu();}
function renderGroupMenu(){const m=el('groupMenu');if(!m)return;const cur=current();m.innerHTML=`<div class="menu-head"><b>Grupos de abas</b><button data-group-new>Novo grupo</button></div><div class="menu-list">${groups.length?groups.map(g=>`<div class="group-item" style="--group-color:${g.color}"><span class="group-dot"></span><div data-group-toggle="${g.id}"><b>${esc(g.name)}</b><small>${tabs.filter(t=>t.groupId===g.id).length} abas${g.collapsed?' · recolhido':''}</small></div><div class="group-actions"><button title="Mudar cor" data-group-color="${g.id}">●</button><button title="Adicionar aba atual" data-group-add="${g.id}">+</button><button title="Apagar grupo" data-group-del="${g.id}">×</button></div></div>`).join(''):'<div class="panel-empty" style="padding:18px">Ainda não tens grupos.</div>'}</div>${cur?.groupId?'<div class="menu-head"><button data-group-remove>Retirar aba atual do grupo</button></div>':''}`;}
function renderProfileMenu(){const m=el('profileMenu');if(!m)return;m.innerHTML=`<div class="menu-head"><b>Perfis</b><button data-profile-new>Novo perfil</button></div><div class="menu-list">${profiles.map(p=>`<div class="profile-item ${p.id===profileId?'active':''}" data-profile-switch="${p.id}" style="--profile-color:${p.color}"><span class="profile-avatar">${esc((p.name?.[0]||'P').toUpperCase())}</span><div><b>${esc(p.name)}</b><small>${p.id===profileId?'Perfil atual':'Mudar para este perfil'}</small></div><span>›</span></div>`).join('')}</div><div class="menu-head"><button data-profile-manage>Gerir perfis</button></div>`;}
function openTabContext(id,x,y){tabContextId=id;const t=tabs.find(a=>a.id===id),m=el('tabContextMenu');if(!t||!m)return;const groupOpts=groups.map(g=>`<button data-ctx-group="${g.id}"><i style="background:${g.color}"></i>${esc(g.name)}</button>`).join('');m.innerHTML=`<button data-ctx="duplicate">Duplicar aba</button><button data-ctx="sleep" ${t.id===active||!t.loaded?'disabled':''}>Adormecer aba</button><button data-ctx="new-group">Novo grupo com esta aba</button>${groupOpts?`<div class="ctx-sep"></div><small>Mover para grupo</small>${groupOpts}`:''}${t.groupId?'<button data-ctx="ungroup">Retirar do grupo</button>':''}<div class="ctx-sep"></div><button data-ctx="close">Fechar aba</button>`;m.style.left=Math.min(x,window.innerWidth-245)+'px';m.style.top=Math.min(y,window.innerHeight-320)+'px';m.classList.add('open');}
function closeTabContext(){el('tabContextMenu')?.classList.remove('open');tabContextId=null;}
async function switchProfile(id){if(id===profileId)return;saveSession();const old=profileId;await invoke('close_profile',{profileId:old}).catch(()=>{});profileId=id;localStorage.setItem(PROFILE_ACTIVE_KEY,id);tabs=[];active=0;seq=0;groups=[];internalView=null;const restored=restoreSession();if(!restored)newTab();else render();document.body.classList.toggle('light',pstr('veyra.theme','dark')==='light');drawFavs();updateProfileButton();await invoke('set_adblock_enabled',{profileId,enabled:adblockEnabled()}).catch(()=>{});await refreshAdblockUi();renderProfileMenu();if(restored)await activateTab(current());}
async function createProfile(){const name=window.prompt('Nome do novo perfil:','Trabalho');if(!name)return;const p={id:'p'+Date.now().toString(36),name:name.trim().slice(0,32)||'Perfil',color:PROFILE_COLORS[profiles.length%PROFILE_COLORS.length]};profiles.push(p);rawSet(PROFILE_LIST_KEY,profiles);await switchProfile(p.id);showView('profile');}
async function deleteProfile(id){if(profiles.length<=1)return window.alert('Tens de manter pelo menos um perfil.');const p=profiles.find(x=>x.id===id);if(!p||!window.confirm(`Apagar o perfil "${p.name}" e os dados locais deste perfil?`))return;if(id===profileId){const other=profiles.find(x=>x.id!==id);await switchProfile(other.id);}profiles=profiles.filter(x=>x.id!==id);rawSet(PROFILE_LIST_KEY,profiles);Object.keys(localStorage).filter(k=>k.startsWith(`veyra.profile.${id}.`)).forEach(k=>localStorage.removeItem(k));await invoke('delete_profile_data',{profileId:id}).catch(()=>{});renderProfileMenu();if(internalView==='profile')renderView('profile');}
function renameProfile(id){const p=profiles.find(x=>x.id===id);if(!p)return;const name=window.prompt('Novo nome do perfil:',p.name);if(!name?.trim())return;p.name=name.trim().slice(0,32);rawSet(PROFILE_LIST_KEY,profiles);updateProfileButton();renderProfileMenu();if(internalView==='profile')renderView('profile');}
function cycleProfileColor(id){const p=profiles.find(x=>x.id===id);if(!p)return;const i=PROFILE_COLORS.indexOf(p.color);p.color=PROFILE_COLORS[(i+1+PROFILE_COLORS.length)%PROFILE_COLORS.length];rawSet(PROFILE_LIST_KEY,profiles);updateProfileButton();renderProfileMenu();if(internalView==='profile')renderView('profile');}
async function sleepTab(id){const t=tabs.find(x=>x.id===id);if(!t||t.id===active||!t.loaded||!t.url)return false;await invoke('close_tab',{profileId,tabId:id}).catch(()=>{});t.loaded=false;t.sleeping=true;saveSession();render();return true;}
async function sleepInactiveTabs(){const mins=sleepMinutes();if(!mins)return;const cutoff=Date.now()-mins*60000;for(const t of tabs){if(t.id!==active&&t.loaded&&t.url&&(t.lastActive||0)<cutoff)await sleepTab(t.id);}}
function duplicateTab(id){const src=tabs.find(x=>x.id===id);if(!src)return;const t={id:++seq,title:src.title,url:src.url,groupId:src.groupId||null,loaded:false,sleeping:false,lastActive:Date.now()};const i=tabs.findIndex(x=>x.id===id);tabs.splice(i+1,0,t);active=t.id;render();activateTab(t);}
function addHistory(url,title){ if(!url||!/^https?:/i.test(url))return; let list=historyList().filter(x=>x.url!==url); list.unshift({url,title:title||new URL(url).hostname,at:Date.now()}); jset('veyra.history',list.slice(0,500)); if(internalView==='history')renderView('history'); }
async function openPage(value){
  const url=makeUrl(value);if(!url)return;const t=current();t.url=url;t.title=new URL(url).hostname.replace(/^www\./,'');t.sleeping=false;t.lastActive=Date.now();internalView=null;document.querySelector('.home').classList.remove('viewing');render();el('status').innerHTML='<i></i>A carregar...';
  try{await invoke('navigate',{profileId,tabId:t.id,url,extensionsEnabled:extensionsEnabled(),adblockEnabled:adblockEnabled()});t.loaded=true;saveSession();el('status').innerHTML='<i></i>'+esc(t.title);}catch(e){el('status').textContent='Erro ao abrir página';console.error(e);}
}
async function activateTab(t){
  if(!t)return;t.sleeping=false;t.lastActive=Date.now();internalView=null;document.querySelector('.home').classList.remove('viewing');render();
  if(!t.url){await invoke('hide_browser');return;}
  if(t.loaded)await invoke('switch_tab',{profileId,tabId:t.id});else{await invoke('navigate',{profileId,tabId:t.id,url:t.url,extensionsEnabled:extensionsEnabled(),adblockEnabled:adblockEnabled()});t.loaded=true;saveSession();}
}
function closeTab(id){const old=tabs.find(t=>t.id===id);if(old?.loaded)invoke('close_tab',{profileId,tabId:id});tabs=tabs.filter(t=>t.id!==id);if(active===id)active=tabs.length?tabs.at(-1).id:0;if(!tabs.length)newTab();else activateTab(current());}
function cycleTab(step){ if(tabs.length<2)return; let i=tabs.findIndex(t=>t.id===active); i=(i+step+tabs.length)%tabs.length; active=tabs[i].id; activateTab(current()); }
function toggleBookmark(){ const t=current(); if(!t?.url)return; let list=saved(); const i=list.findIndex(x=>x.url===t.url); if(i>=0)list.splice(i,1); else list.unshift({url:t.url,title:t.title,created:Date.now()}); jset('veyra.bookmarks',list.slice(0,100)); updateStar(); drawFavs(); if(internalView==='bookmarks')renderView('bookmarks'); }
function addFavoritePrompt(){
  const input=window.prompt('Endereço do site que queres adicionar:','https://'); if(!input)return; const url=makeUrl(input); let title=window.prompt('Nome do favorito:',new URL(url).hostname.replace(/^www\./,'')); if(!title)title=new URL(url).hostname;
  let list=saved().filter(x=>x.url!==url); list.unshift({url,title,created:Date.now()}); jset('veyra.bookmarks',list.slice(0,100)); drawFavs(); if(internalView==='bookmarks')renderView('bookmarks');
}
function goHome(){ const t=current(); t.url=''; t.title='Nova aba'; internalView=null; render(); invoke('hide_browser'); document.querySelector('.home').classList.remove('viewing'); document.querySelectorAll('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='home')); el('status').innerHTML='<i></i>Pronto'; }
function showView(name){ internalView=name; invoke('hide_browser'); render(); document.querySelector('.home').classList.add('viewing'); document.querySelectorAll('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); renderView(name); el('appMenu').classList.remove('open'); el('status').innerHTML='<i></i>Pronto'; }
function rowIcon(text){ return `<div class="ico">${esc(text)}</div>`; }
function renderView(name){
  const p=el('viewPanel'); if(!p)return;
  if(name==='bookmarks'){
    const a=saved(); p.innerHTML=`<div class="panel-head"><div><h2>Marcadores</h2><p>Os teus favoritos guardados localmente no Veyra.</p></div><div class="panel-actions"><button class="vbtn primary" data-action="add-favorite">Adicionar</button></div></div><div class="panel-grid">${a.length?a.map((x,i)=>`<div class="list-row">${rowIcon('☆')}<div class="meta"><b>${esc(x.title)}</b><small>${esc(x.url)}</small></div><div class="row-actions"><button data-open="${esc(x.url)}">Abrir</button><button data-del-bookmark="${i}">Remover</button></div></div>`).join(''):'<div class="panel-empty">Ainda não tens marcadores. Usa a estrela na barra de endereço.</div>'}</div>`;
  } else if(name==='history'){
    const a=historyList(); p.innerHTML=`<div class="panel-head"><div><h2>Histórico</h2><p>Páginas visitadas neste perfil.</p></div><div class="panel-actions"><button class="vbtn danger" data-action="clear-history">Limpar histórico</button></div></div><div class="panel-grid">${a.length?a.map(x=>`<div class="list-row">${rowIcon('◷')}<div class="meta"><b>${esc(x.title)}</b><small>${esc(x.url)} · ${new Date(x.at).toLocaleString()}</small></div><div class="row-actions"><button data-open="${esc(x.url)}">Abrir</button></div></div>`).join(''):'<div class="panel-empty">O histórico está vazio.</div>'}</div>`;
  } else if(name==='downloads'){
    const a=downloads(); p.innerHTML=`<div class="panel-head"><div><h2>Transferências</h2><p>Ficheiros transferidos pelo Veyra.</p></div><div class="panel-actions"><button class="vbtn" data-action="open-downloads">Abrir pasta</button><button class="vbtn" data-action="clear-finished-downloads">Limpar concluídos</button><button class="vbtn danger" data-action="clear-downloads">Limpar lista</button></div></div><div class="panel-grid">${a.length?a.map((x,i)=>`<div class="list-row">${rowIcon(x.success===false?'!':'⇩')}<div class="meta"><b>${esc(x.name||x.url)}</b><small>${esc(x.path||x.url)}${x.at?` · ${new Date(x.at).toLocaleString()}`:''}</small><span class="download-state">${x.success===false?'Falhou':x.finished?'Concluído':'A transferir…'}</span></div><div class="row-actions">${x.finished&&x.path&&x.success!==false?`<button data-reveal-download="${i}">Mostrar na pasta</button>`:''}<button data-del-download="${i}">Remover</button></div></div>`).join(''):'<div class="panel-empty">Ainda não existem transferências.</div>'}</div>`;
  }else if(name==='groups'){
    p.innerHTML=`<div class="panel-head"><div><h2>Grupos de abas</h2><p>Organiza as abas do perfil <b>${esc(profileMeta()?.name||'Perfil')}</b> por contexto e cor.</p></div><div class="panel-actions"><button class="vbtn primary" data-action="new-group">Novo grupo</button></div></div><div class="panel-grid">${groups.length?groups.map(g=>`<div class="list-row" style="border-left:4px solid ${g.color}"><div class="ico" style="color:${g.color}">●</div><div class="meta"><b>${esc(g.name)}</b><small>${tabs.filter(t=>t.groupId===g.id).length} abas · ${g.collapsed?'Recolhido':'Expandido'}</small></div><div class="row-actions"><button data-view-group-add="${g.id}">Adicionar aba atual</button><button data-view-group-toggle="${g.id}">${g.collapsed?'Expandir':'Recolher'}</button><button data-view-group-color="${g.id}">Cor</button><button data-view-group-del="${g.id}">Apagar</button></div></div>`).join(''):'<div class="panel-empty">Ainda não tens grupos. Cria um e a aba atual entra automaticamente nele.</div>'}</div>`;
  }else if(name==='menu'){
    p.innerHTML=`<div class="panel-head"><div><h2>Menu Veyra</h2><p>Acesso rápido às ferramentas do browser.</p></div></div><div class="settings-grid menu-grid"><button class="setting-card menu-card" data-menu-view="bookmarks"><h3>☆ Marcadores</h3><p>Ver e gerir favoritos.</p></button><button class="setting-card menu-card" data-menu-view="history"><h3>◷ Histórico</h3><p>Páginas visitadas neste perfil.</p></button><button class="setting-card menu-card" data-menu-view="downloads"><h3>⇩ Transferências</h3><p>Downloads e ficheiros concluídos.</p></button><button class="setting-card menu-card" data-menu-view="extensions"><h3>✣ Extensões</h3><p>Proton Pass e extensões Chromium.</p></button><button class="setting-card menu-card" data-menu-view="groups"><h3>◫ Grupos de abas</h3><p>Organizar abas por grupo e cor.</p></button><button class="setting-card menu-card" data-menu-view="profile"><h3>◉ Perfis</h3><p>Trocar e gerir perfis isolados.</p></button><button class="setting-card menu-card" data-menu-view="settings"><h3>⚙ Definições</h3><p>Pesquisa, aparência e sleeping tabs.</p></button></div>`;
  }else if(name==='extensions'){
    const enabled=extensionsEnabled();p.innerHTML=`<div class="panel-head"><div><h2>Extensões</h2><p>Extensões Chromium deste perfil: <b>${esc(profileMeta()?.name||'Perfil')}</b>.</p></div><div class="panel-actions"><button class="vbtn" data-action="open-extensions-folder">Abrir pasta</button><button class="vbtn primary" data-action="install-extension">Adicionar desempacotada</button><button class="vbtn ${enabled?'danger':'primary'}" data-action="toggle-extensions">${enabled?'Desativar extensões':'Ativar extensões'}</button></div></div><div class="extension-card"><img src="assets/proton-pass.png"><div><h3>Proton Pass</h3><p>Gestor de palavras-passe com autofill nas páginas deste perfil.</p><span id="protonStatus" class="status">A verificar…</span></div><div class="extension-actions"><button class="vbtn primary" data-open="https://pass.proton.me">Abrir Proton Pass</button><button class="vbtn" data-open="https://chromewebstore.google.com/detail/proton-pass-free-password/ghmbeldphafepmbegfdlkpapadhbakde">Web Store</button></div></div><div class="panel-head" style="margin-top:24px"><div><h2 style="font-size:20px">Instaladas</h2><p>O Proton Pass vem incluído. Podes adicionar outras extensões Chromium desempacacotadas.</p></div></div><div id="extensionsList" class="panel-grid"><div class="panel-empty">A carregar extensões…</div></div><div class="panel-grid" style="margin-top:14px"><div class="setting-card"><h3>Isolamento por perfil</h3><p>Cada perfil usa um diretório WebView2 próprio para cookies, logins e dados dos sites. Ativar/desativar extensões aplica-se apenas ao perfil atual.</p></div></div>`;
    invoke('extension_info',{profileId}).then(info=>{const st=el('protonStatus');if(st)st.textContent=!enabled?`Desativada neste perfil · v${info.version}`:(info.installed?`Ativa · v${info.version}`:(info.ready?`Carregada · v${info.version}`:'Extensão não encontrada'));}).catch(()=>{const st=el('protonStatus');if(st)st.textContent='Erro ao verificar';});refreshExtensionsList();  }else if(name==='settings'){
    const eng=pstr('veyra.search','google');
    p.innerHTML=`<div class="panel-head"><div><h2>Definições</h2><p>Definições do perfil <b>${esc(profileMeta()?.name||'Perfil')}</b>.</p></div></div><div class="settings-grid"><div class="setting-card"><h3>Motor de pesquisa</h3><p>Usado quando escreves palavras na barra de endereço.</p><select id="searchEngine"><option value="google">Google</option><option value="duck">DuckDuckGo</option><option value="bing">Bing</option></select></div><div class="setting-card"><h3>Idioma / Language</h3><p>Idioma da interface do Veyra.</p><select id="languageSelect"><option value="pt">Português</option><option value="en">English</option></select></div><div class="setting-card"><h3>Aparência</h3><p>Alterna entre a interface escura e clara neste perfil.</p><button class="vbtn" data-action="toggle-theme">Alternar tema</button></div><div class="setting-card"><h3>Dados de navegação</h3><p>Remove cookies, cache e armazenamento apenas deste perfil.</p><button class="vbtn danger" data-action="clear-browser-data">Limpar dados deste perfil</button></div><div class="setting-card"><h3>AdBlock integrado</h3><p>Bloqueia pedidos de anúncios conhecidos diretamente no motor WebView2, sem extensão.</p><div class="adblock-setting"><button id="adblockToggleBtn" class="vbtn ${adblockEnabled()?'danger':'primary'}" data-action="toggle-adblock">${adblockEnabled()?'Desativar AdBlock':'Ativar AdBlock'}</button><span id="adblockStats" class="download-state">A carregar…</span></div></div><div class="setting-card"><h3>Sleeping tabs</h3><p>Descarrega abas inativas da memória e recarrega-as quando voltares.</p><select id="sleepMinutes"><option value="0">Nunca</option><option value="5">5 minutos</option><option value="10">10 minutos</option><option value="15">15 minutos</option><option value="30">30 minutos</option><option value="60">1 hora</option></select></div><div class="setting-card"><h3>Atualizações</h3><p id="updateStatus">A obter versão atual…</p><button id="checkUpdateBtn" class="vbtn" data-action="check-update">Verificar atualizações</button></div></div>`;
    el('searchEngine').value=eng;el('searchEngine').onchange=e=>pset('veyra.search',e.target.value);const ls=el('languageSelect');if(ls){ls.value=getLanguage();ls.onchange=e=>{setLanguage(e.target.value);renderView('settings');};}const sm=el('sleepMinutes');if(sm){sm.value=String(sleepMinutes());sm.onchange=e=>pset('veyra.sleep.minutes',e.target.value);}invoke('app_version').then(v=>{const s=el('updateStatus');if(s)s.textContent=`Versão atual: ${v}`;});refreshAdblockUi();
  }else if(name==='profile'){
    p.innerHTML=`<div class="panel-head"><div><h2>Perfis</h2><p>Separa trabalho, pessoal e outras sessões do browser.</p></div><div class="panel-actions"><button class="vbtn primary" data-action="new-profile">Novo perfil</button></div></div><div class="profile-grid">${profiles.map(x=>`<div class="profile-tile ${x.id===profileId?'active':''}" style="--profile-color:${x.color}"><span class="profile-avatar">${esc((x.name?.[0]||'P').toUpperCase())}</span><div class="grow"><h3>${esc(x.name)}</h3><p>${x.id===profileId?'Perfil atual · cookies e sessão isolados':'Dados, abas e logins separados'}</p></div><div class="row-actions">${x.id!==profileId?`<button data-switch-profile="${x.id}">Abrir</button>`:''}<button data-rename-profile="${x.id}">Renomear</button><button data-color-profile="${x.id}" style="color:${x.color}">Cor</button>${profiles.length>1?`<button data-delete-profile="${x.id}">Apagar</button>`:''}</div></div>`).join('')}</div>`;
  }
}
function updateSidebarLanguage(){const n=el('favoritesLabel');if(n)n.textContent=document.documentElement.lang==='en'?'Favorites':'Favoritos';}
async function refreshAdblockUi(){try{const info=await invoke('adblock_info',{profileId});const top=el('topAdblock'),count=el('adblockCount'),stats=el('adblockStats');if(top)top.classList.toggle('off',!info.enabled);if(count)count.textContent=String(info.blocked||0);if(stats)stats.textContent=getLanguage()==='en'?`${info.blocked||0} blocked · ${info.rules||0} rules`:`${info.blocked||0} bloqueados · ${info.rules||0} regras`;return info;}catch(e){console.error('AdBlock info',e);return null;}}
function drawFavs(){ const host=el('sideFavs'); host.textContent=''; const list=saved(); const defaults=list.length?list.slice(0,6):[{title:'YouTube',url:'https://youtube.com'},{title:'Google',url:'https://google.com'},{title:'ChatGPT',url:'https://chatgpt.com'},{title:'GitHub',url:'https://github.com'}]; defaults.forEach(f=>{const b=document.createElement('button');b.textContent='◉  '+f.title;b.onclick=()=>openPage(f.url);host.append(b);}); }
function pushDownload(d){ let a=downloads(); const idx=a.findIndex(x=>x.url===d.url&&!x.finished); const now=Date.now(); if(idx>=0)a[idx]={...a[idx],...d,at:a[idx].at||now}; else a.unshift({...d,at:now}); jset('veyra.downloads',a.slice(0,200)); if(internalView==='downloads')renderView('downloads'); }
async function refreshExtensionsList(){const host=el('extensionsList');if(!host)return;try{const items=await invoke('list_extensions');host.innerHTML=items.length?items.map(x=>`<div class="list-row"><div class="ico">${x.protected?'◆':'✣'}</div><div class="meta"><b>${esc(x.name)}</b><small>v${esc(x.version)} · Manifest V${esc(x.manifestVersion)} · ${esc(x.folder)}</small></div><div class="row-actions">${x.protected?'<span class="extension-badge">Bundled</span>':`<button data-remove-extension="${esc(x.folder)}">Remover</button>`}</div></div>`).join(''):'<div class="panel-empty">Não existem extensões instaladas.</div>';}catch(e){host.innerHTML='<div class="panel-empty">Erro ao listar extensões.</div>';console.error(e);}}
window.addEventListener('DOMContentLoaded',()=>{
  initProfiles();const restored=restoreSession();if(!restored)newTab();else render();document.body.classList.toggle('light',pstr('veyra.theme','dark')==='light');updateProfileButton();initI18n();updateSidebarLanguage();window.addEventListener('veyra-language-changed',updateSidebarLanguage);invoke('set_adblock_enabled',{profileId,enabled:adblockEnabled()}).then(refreshAdblockUi).catch(console.error);
  listen('veyra-page',e=>{const payload=e.payload||{};if(payload.profileId&&payload.profileId!==profileId)return;const t=tabs.find(x=>x.id===Number(payload.tabId));if(!t||!payload.url)return;t.url=payload.url;t.loaded=true;addHistory(t.url,t.title);saveSession();if(t.id===active&&!internalView){el('address').value=t.url;updateStar();}});
  listen('veyra-title',e=>{const payload=e.payload||{};if(payload.profileId&&payload.profileId!==profileId)return;const t=tabs.find(x=>x.id===Number(payload.tabId));if(!t||!payload.title)return;t.title=payload.title;saveSession();if(t.id===active)render();addHistory(t.url,t.title);});
  listen('veyra-download',e=>{if(e.payload?.profileId&&e.payload.profileId!==profileId)return;pushDownload(e.payload);});
  listen('veyra-adblock',e=>{if(e.payload?.profileId&&e.payload.profileId!==profileId)return;const n=el('adblockCount');if(n)n.textContent=String(e.payload?.total||0);const s=el('adblockStats');if(s)s.textContent=getLanguage()==='en'?`${e.payload?.total||0} blocked`:`${e.payload?.total||0} bloqueados`;});
  listen('veyra-new-window',e=>{if(e.payload?.profileId&&e.payload.profileId!==profileId)return;const url=e.payload?.url;if(url){newTab(current()?.groupId||null);setTimeout(()=>openPage(url),80);}});
  listen('veyra-accelerator',e=>{if(e.payload?.profileId&&e.payload.profileId!==profileId)return;const a=e.payload?.action;if(!a)return;if(a==='new-tab')newTab();else if(a==='close-tab')closeTab(active);else if(a==='focus-address'){el('address').focus();el('address').select();}else if(a==='reload')invoke('browser_reload',{profileId,tabId:active});else if(a==='history')showView('history');else if(a==='downloads')showView('downloads');else if(a==='next-tab')cycleTab(1);else if(a==='prev-tab')cycleTab(-1);else if(a==='back')invoke('browser_back',{profileId,tabId:active});else if(a==='forward')invoke('browser_forward',{profileId,tabId:active});});
  const autoTest=new URLSearchParams(location.search).get('autotest'); if(autoTest)setTimeout(()=>openPage(autoTest),400); else if(restored)setTimeout(()=>activateTab(current()),180);
  el('go').onclick=()=>openPage(el('address').value);el('newTab').onclick=()=>newTab();el('back').onclick=()=>invoke('browser_back',{profileId,tabId:active});el('forward').onclick=()=>invoke('browser_forward',{profileId,tabId:active});el('reload').onclick=()=>invoke('browser_reload',{profileId,tabId:active});el('home').onclick=goHome;el('bookmark').onclick=toggleBookmark;
  el('topAdblock').onclick=async()=>{const next=!adblockEnabled();pset('veyra.adblock.enabled',next?'1':'0');await invoke('set_adblock_enabled',{profileId,enabled:next});await refreshAdblockUi();};el('topDownloads').onclick=()=>showView('downloads');el('topExtensions').onclick=()=>showView('extensions');el('topProfile').onclick=e=>{e.stopPropagation();if(current()?.url&&!internalView)return showView('profile');renderProfileMenu();el('groupMenu').classList.remove('open');el('profileMenu').classList.toggle('open');};el('groupTabs').onclick=e=>{e.stopPropagation();if(current()?.url&&!internalView)return showView('groups');renderGroupMenu();el('profileMenu').classList.remove('open');el('groupMenu').classList.toggle('open');};el('topMenu').onclick=e=>{e.stopPropagation();el('profileMenu').classList.remove('open');el('groupMenu').classList.remove('open');if(current()?.url&&!internalView)return showView('menu');el('appMenu').classList.toggle('open');};
  el('themeToggle').onclick=()=>{const light=!document.body.classList.contains('light');document.body.classList.toggle('light',light);pset('veyra.theme',light?'light':'dark');};
  el('address').onkeydown=e=>{if(e.key==='Enter')openPage(e.target.value);};el('search').onsubmit=e=>{e.preventDefault();openPage(el('startSearch').value);};
  el('tabs').onclick=e=>{if(suppressTabClick){suppressTabClick=false;return;}if(e.target.dataset.close)return closeTab(Number(e.target.dataset.close));const pill=e.target.closest('.tab-group-pill');if(pill){const g=groups.find(x=>x.id===pill.dataset.groupId);if(g){g.collapsed=!g.collapsed;render();}return;}const tab=e.target.closest('.tab');if(tab){const prev=current();if(prev)prev.lastActive=Date.now();active=Number(tab.dataset.id);activateTab(current());}};
  el('tabs').oncontextmenu=e=>{const tab=e.target.closest('.tab');if(!tab)return;e.preventDefault();openTabContext(Number(tab.dataset.id),e.clientX,e.clientY);};
  el('tabs').onauxclick=e=>{if(e.button!==1)return;const tab=e.target.closest('.tab');if(!tab)return;e.preventDefault();closeTab(Number(tab.dataset.id));};
  el('tabs').onmousedown=e=>{if(e.button!==0||e.target.dataset.close)return;const tab=e.target.closest('.tab');if(!tab)return;dragTabId=Number(tab.dataset.id);dragStartX=e.clientX;dragStartY=e.clientY;draggingTabs=false;};
  document.addEventListener('mousemove',e=>{if(!dragTabId)return;if(!draggingTabs&&Math.hypot(e.clientX-dragStartX,e.clientY-dragStartY)>7){draggingTabs=true;document.querySelector(`.tab[data-id="${dragTabId}"]`)?.classList.add('dragging');}if(!draggingTabs)return;document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('.tab,.tab-group-pill');if(hit&&Number(hit.dataset.id)!==dragTabId)hit.classList.add('drag-over');});
  document.addEventListener('mouseup',e=>{if(!dragTabId)return;const id=dragTabId;const wasDragging=draggingTabs;dragTabId=null;draggingTabs=false;document.querySelector(`.tab[data-id="${id}"]`)?.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));if(!wasDragging)return;const dragged=tabs.find(x=>x.id===id);const hit=document.elementFromPoint(e.clientX,e.clientY);const pill=hit?.closest('.tab-group-pill');const target=hit?.closest('.tab');if(dragged){if(pill){dragged.groupId=pill.dataset.groupId;}else if(target&&Number(target.dataset.id)!==id){const targetId=Number(target.dataset.id),ti=tabs.find(x=>x.id===targetId);dragged.groupId=ti?.groupId||null;const from=tabs.findIndex(x=>x.id===id);const [moved]=tabs.splice(from,1);const to=tabs.findIndex(x=>x.id===targetId);tabs.splice(Math.max(0,to),0,moved);}else if(hit?.closest('#tabs')){dragged.groupId=null;const from=tabs.findIndex(x=>x.id===id);const [moved]=tabs.splice(from,1);tabs.push(moved);}render();}suppressTabClick=true;setTimeout(()=>suppressTabClick=false,0);});
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>b.dataset.view==='home'?goHome():showView(b.dataset.view));  const quickSites=[['YouTube','youtube.com','youtube','yt'],['Google','google.com','google','google'],['WhatsApp','web.whatsapp.com','whatsapp','wa'],['Netflix','netflix.com','netflix','netflix'],['Instagram','instagram.com','instagram','insta'],['GitHub','github.com','github','github'],['Adicionar','','','add']];
  quickSites.forEach(x=>{const b=document.createElement('button');b.className=x[3];const icon=x[2]?`<img src="assets/sites/${x[2]}.png">`:'+';b.innerHTML=`<i>${icon}</i><span>${x[0]}</span>`;b.onclick=()=>x[1]?openPage(x[1]):addFavoritePrompt();el('quick').append(b);});
  drawFavs(); const addFav=el('addFavorite'); if(addFav)addFav.onclick=addFavoritePrompt;
  const tick=()=>{const d=new Date();el('clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}; tick(); setInterval(tick,30000);setInterval(sleepInactiveTabs,SLEEP_CHECK_MS);
  el('winMin').onclick=()=>invoke('window_minimize').catch(console.error);el('winMax').onclick=()=>invoke('window_toggle_maximize').catch(console.error);el('winClose').onclick=()=>invoke('window_close').catch(console.error);
  const topbar=document.querySelector('.topbar');topbar.addEventListener('mousedown',e=>{if(e.button!==0)return;if(e.target.closest('button,.tab,.window-tools,input,a'))return;invoke('window_start_dragging').catch(console.error);});topbar.addEventListener('dblclick',e=>{if(e.target.closest('button,.tab,.window-tools,input,a'))return;invoke('window_toggle_maximize').catch(console.error);});
  document.addEventListener('click',e=>{if(!e.target.closest('#appMenu')&&!e.target.closest('#topMenu'))el('appMenu').classList.remove('open');if(!e.target.closest('#profileMenu')&&!e.target.closest('#topProfile'))el('profileMenu').classList.remove('open');if(!e.target.closest('#groupMenu')&&!e.target.closest('#groupTabs'))el('groupMenu').classList.remove('open');if(!e.target.closest('#tabContextMenu'))closeTabContext();});
  el('profileMenu').addEventListener('click',async e=>{const sw=e.target.closest('[data-profile-switch]');if(sw){await switchProfile(sw.dataset.profileSwitch);el('profileMenu').classList.remove('open');return;}if(e.target.closest('[data-profile-new]')){await createProfile();el('profileMenu').classList.remove('open');return;}if(e.target.closest('[data-profile-manage]')){el('profileMenu').classList.remove('open');showView('profile');}});
  el('groupMenu').addEventListener('click',e=>{const t=e.target.closest('[data-group-toggle]');if(t){const g=groups.find(x=>x.id===t.dataset.groupToggle);if(g){g.collapsed=!g.collapsed;render();renderGroupMenu();}return;}const add=e.target.closest('[data-group-add]');if(add)return assignGroup(add.dataset.groupAdd);const col=e.target.closest('[data-group-color]');if(col)return cycleGroupColor(col.dataset.groupColor);const del=e.target.closest('[data-group-del]');if(del)return deleteGroup(del.dataset.groupDel);if(e.target.closest('[data-group-new]'))return createGroup();if(e.target.closest('[data-group-remove]'))return assignGroup(null);});
  el('tabContextMenu').addEventListener('click',async e=>{const id=tabContextId,t=tabs.find(x=>x.id===id);if(!t)return closeTabContext();const gi=e.target.closest('[data-ctx-group]');if(gi){t.groupId=gi.dataset.ctxGroup;render();return closeTabContext();}const a=e.target.closest('[data-ctx]')?.dataset.ctx;if(!a)return;if(a==='duplicate')duplicateTab(id);else if(a==='sleep')await sleepTab(id);else if(a==='ungroup'){t.groupId=null;render();}else if(a==='close')closeTab(id);else if(a==='new-group'){const name=window.prompt('Nome do grupo:','Novo grupo');if(name){const g={id:'g'+Date.now().toString(36),name:name.trim()||'Grupo',color:PROFILE_COLORS[groups.length%PROFILE_COLORS.length],collapsed:false};groups.push(g);t.groupId=g.id;render();}}closeTabContext();});
  el('viewPanel').addEventListener('click',async e=>{
    const menuView=e.target.closest('[data-menu-view]')?.dataset.menuView;if(menuView){showView(menuView);return;}
    const open=e.target.dataset.open; if(open)return openPage(open);
    if(e.target.dataset.delBookmark!==undefined){let a=saved();a.splice(Number(e.target.dataset.delBookmark),1);jset('veyra.bookmarks',a);drawFavs();renderView('bookmarks');return;}
    if(e.target.dataset.delDownload!==undefined){let a=downloads();a.splice(Number(e.target.dataset.delDownload),1);jset('veyra.downloads',a);renderView('downloads');return;}
    if(e.target.dataset.revealDownload!==undefined){const item=downloads()[Number(e.target.dataset.revealDownload)];if(item?.path){try{await invoke('reveal_download',{path:item.path});}catch(err){window.alert(String(err));}}return;}
    if(e.target.dataset.removeExtension){if(!window.confirm('Remover esta extensão do Veyra?'))return;try{await invoke('remove_extension',{folder:e.target.dataset.removeExtension});await invoke('close_profile',{profileId}).catch(()=>{});tabs.forEach(t=>t.loaded=false);saveSession();await refreshExtensionsList();}catch(err){window.alert(String(err));}return;}
    if(e.target.dataset.switchProfile){await switchProfile(e.target.dataset.switchProfile);showView('profile');return;}
    if(e.target.dataset.renameProfile){renameProfile(e.target.dataset.renameProfile);return;}
    if(e.target.dataset.colorProfile){cycleProfileColor(e.target.dataset.colorProfile);return;}
    if(e.target.dataset.deleteProfile){await deleteProfile(e.target.dataset.deleteProfile);return;}
    if(e.target.dataset.viewGroupAdd){assignGroup(e.target.dataset.viewGroupAdd);renderView('groups');return;}
    if(e.target.dataset.viewGroupToggle){const g=groups.find(x=>x.id===e.target.dataset.viewGroupToggle);if(g){g.collapsed=!g.collapsed;render();renderView('groups');}return;}
    if(e.target.dataset.viewGroupColor){cycleGroupColor(e.target.dataset.viewGroupColor);renderView('groups');return;}
    if(e.target.dataset.viewGroupDel){deleteGroup(e.target.dataset.viewGroupDel);renderView('groups');return;}
    const a=e.target.dataset.action;
    if(a==='add-favorite')addFavoritePrompt();
    else if(a==='new-group'){createGroup();renderView('groups');}
    else if(a==='new-profile')await createProfile();
    else if(a==='clear-history'){jset('veyra.history',[]);renderView('history');}
    else if(a==='clear-downloads'){jset('veyra.downloads',[]);renderView('downloads');}
    else if(a==='clear-finished-downloads'){jset('veyra.downloads',downloads().filter(x=>!x.finished));renderView('downloads');}
    else if(a==='open-downloads')await invoke('open_downloads_folder');
    else if(a==='toggle-theme')el('themeToggle').click();
    else if(a==='open-extensions-folder')await invoke('open_extensions_folder');
    else if(a==='install-extension'){const path=window.prompt('Caminho da pasta da extensão desempacotada (tem de conter manifest.json):','');if(path?.trim()){try{const info=await invoke('install_extension_folder',{sourcePath:path.trim()});await invoke('close_profile',{profileId}).catch(()=>{});tabs.forEach(t=>t.loaded=false);saveSession();await refreshExtensionsList();window.alert('Extensão '+info.name+' instalada. Será carregada quando abrires uma página.');}catch(err){window.alert(String(err));}}}
    else if(a==='toggle-extensions'){pset('veyra.extensions.enabled',extensionsEnabled()?'0':'1');await invoke('close_profile',{profileId}).catch(()=>{});tabs.forEach(t=>t.loaded=false);saveSession();renderView('extensions');}
    else if(a==='toggle-adblock'){const next=!adblockEnabled();pset('veyra.adblock.enabled',next?'1':'0');await invoke('set_adblock_enabled',{profileId,enabled:next});await refreshAdblockUi();renderView('settings');}
    else if(a==='check-update'){const s=el('updateStatus'),b=el('checkUpdateBtn');if(s)s.textContent='A verificar atualizações…';if(b)b.disabled=true;try{const info=await invoke('check_for_update');if(info.available){if(s)s.textContent=`Atualização v${info.version} disponível (atual: v${info.currentVersion}).`;if(b){b.textContent='Instalar atualização';b.dataset.action='install-update';b.classList.add('primary');}}else{if(s)s.textContent=`Veyra v${info.currentVersion} está atualizado.`;}}catch(err){if(s)s.textContent='Não foi possível verificar o GitHub Releases.';}finally{if(b)b.disabled=false;}}
    else if(a==='install-update'){const s=el('updateStatus'),b=el('checkUpdateBtn');if(s)s.textContent='A transferir e instalar atualização…';if(b)b.disabled=true;try{await invoke('install_update');}catch(err){if(s)s.textContent='Falha ao instalar atualização: '+String(err);if(b)b.disabled=false;}}
    else if(a==='clear-browser-data'){await invoke('clear_browser_data',{profileId});jset('veyra.history',[]);jset('veyra.downloads',[]);e.target.textContent='Dados limpos ✓';}
  });
  document.addEventListener('keydown',e=>{
    const mod=e.ctrlKey||e.metaKey;
    if(mod&&e.key==='Tab'){e.preventDefault();cycleTab(e.shiftKey?-1:1);}
    else if(mod&&e.key.toLowerCase()==='l'){e.preventDefault();el('address').focus();el('address').select();}
    else if(mod&&e.key.toLowerCase()==='t'){e.preventDefault();newTab();}
    else if(mod&&e.key.toLowerCase()==='w'){e.preventDefault();closeTab(active);}
    else if(mod&&e.key.toLowerCase()==='r'){e.preventDefault();invoke('browser_reload',{profileId,tabId:active});}
    else if(mod&&e.key.toLowerCase()==='h'){e.preventDefault();showView('history');}
    else if(mod&&e.key.toLowerCase()==='j'){e.preventDefault();showView('downloads');}
    else if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();invoke('browser_back',{profileId,tabId:active});}
    else if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();invoke('browser_forward',{profileId,tabId:active});}
  });
});